import datetime
import streamlit as st
from streamlit_extras.switch_page_button import switch_page

# Define carousel items (feature pages)
features = [
    {"title": "AI_Chatbot", "display_title": "AI Chatbot", "description": "Get instant answers to regulatory queries.", "img": "https://business.cornell.edu/wp-content/uploads/sites/2/2024/07/Robot-working-on-computer-600x400.jpg"},
    {"title": "Comparison_Tool", "display_title": "Comparison Tool", "description": "Analyze differences in CCS regulations.", "img": "https://static.vecteezy.com/system/resources/thumbnails/004/581/113/small_2x/pros-and-cons-comparison-for-making-business-decisions-advantage-positive-and-negative-analysis-information-list-concept-thoughtful-businessman-listing-business-pros-and-cons-to-consider-benefits-vector.jpg"},
    {"title": "Compliance_Score", "display_title": "Compliance Score", "description": "Track CCS policy compliance measures.", "img": "https://igadvisory.co.za/wp-content/uploads/2022/12/depositphotos_132367240-stock-photo-compliance-concept-the-meeting-at.webp"},
    {"title": "Policy_Advisor", "display_title": "Policy Advisor", "description": "Understand key compliance requirements.", "img": "https://media.istockphoto.com/id/671968496/photo/help-support-advice-guidance-singpost.jpg?s=612x612&w=0&k=20&c=DB2CoqyohiuxYxqjZ8-GD2OYogch8nw2DfDnadl5jEM="},
    {"title": "Daily_News", "display_title": "Daily News", "description": "Stay updated with the latest regulatory changes.", "img": "https://static.vecteezy.com/system/resources/thumbnails/011/585/604/small_2x/business-newspaper-on-wooden-desk-with-glasses-and-coffee-cup-daily-newspaper-mock-up-concept-photo.jpg"},
]
st.markdown(
    f"<div style='text-align: right;'>📅 <strong>Up to date:</strong> {datetime.date.today().strftime('%B %d, %Y')}</div>",
    unsafe_allow_html=True
)
# Display AI-generated warning at the top
st.warning(
    "⚠️ This content is generated by an AI system. Responses may not always be accurate or up to date. "
    "Please verify critical information from official sources."
)

# Main Page Title
st.markdown("""
    <h1 style='text-align: center; color: #28a745;'>🌍 Cécilia </h1>
    <p style='text-align: center; font-size: 18px; color: #555;'>Your go-to platform for tracking, analyzing, and comparing CCS regulations globally.</p>
""", unsafe_allow_html=True)

st.markdown("## 🎯 Why This Tool?")
st.info("CCS regulations are constantly evolving, making it crucial to stay updated. However, navigating complex regulatory frameworks daily can be overwhelming. That's why we built this tool—providing you with **comparative analysis across multiple parameters and regions** while also offering **insights and guidance** to support your next CCS project.")

st.markdown("## 📝 Features")

# Initialize session state for carousel index
if "carousel_index" not in st.session_state:
    st.session_state["carousel_index"] = 0

# Navigation buttons should update the index before rendering content
col1, col2, col3 = st.columns([2, 6, 2])  # Buttons at the edges

with col1:
    prev_clicked = st.button("⬅️ Previous", key="prev_button", use_container_width=True)

with col3:
    next_clicked = st.button("Next ➡️", key="next_button", use_container_width=True)

# Update index before rendering content
if prev_clicked:
    st.session_state["carousel_index"] = (st.session_state["carousel_index"] - 1) % len(features)
elif next_clicked:
    st.session_state["carousel_index"] = (st.session_state["carousel_index"] + 1) % len(features)

# Get the current slide
current_index = st.session_state["carousel_index"]
feature = features[current_index]

# Display clickable title (uses switch_page to navigate)
with col2:
    if st.button(feature["display_title"], key=f"title_{current_index}", use_container_width=True):
        switch_page(feature["title"])  # Instantly navigate without reload

# Display the image
st.image(feature["img"], use_container_width=True)

# Display the description centered
st.markdown(
    f"<p style='text-align: center; font-size: 18px; color: black;'>{feature['description']}</p>",
    unsafe_allow_html=True
)
